### ISSUE TITLE
Bug with no-descending-specificity

### ISSUE THREAD

**Issue by smutnyleszek** [AtomLinter/linter-stylelint#133]
I would expect `[data-foo]:not(:last-child)` to be identified as more specific than `[data-foo]`. I get error:

```
Expected selector "[data-foo]:not(:last-child)" to come before selector "[data-foo]" (no-descending-specificity)
```

```css
[data-foo] {
    display: block;
}

[data-foo]:not(:last-child) {
    display: none;
}
```

```json
{
    "rules": {
        "no-descending-specificity": [true, {
            "severity": "error"
        }]
    }
}
```

I use `stylelint 5.0.1` with `linter-stylelint 2.0.1`. When running from CLI there is no error.
