### ISSUE TITLE
no-duplicate-selectors bug

### ISSUE THREAD

**Issue by revyh** [AtomLinter/linter-stylelint#138]
Minimal setup to reproduce:

.stylelintrc.yml
```yaml
---
  rules:
    no-duplicate-selectors: [true, {severity: error}]
```

blah.css
```scss
.blah {
  color: red;
}
```

CLI output says that there is no error. I use `stylelint 5.1` and `linter-stylelint 2.0.1`.

Looks like text from editor is duplicated somehow when it's passed to stylelint. If that's true, it may explain #133.

Setup [blah.zip](https://github.com/AtomLinter/linter-stylelint/files/187444/blah.zip)
