### ISSUE TITLE
"Unable to run stylelint: this.spacesFromStart is not a function" when writing out a property.

### ISSUE THREAD

**Issue by joeyred** [AtomLinter/linter-stylelint#321]
# The Problem

This error keeps getting thrown, usually when I'm adding a property above a nested rule working in scss. The error ends up popping up with Atom's notification system for errors. While this doesn't crash anything, and the listing still operates, it gets annoying having the errors pile up until i can finally finish writing the rule, and then having to close out the notifications.

# Example

## Code
```scss
&.active {
    position: fixed;
    top:

    .tab {
      h2 {
        flex: auto;
      }
   }
}
```
## Screenshots
![screen shot 2017-02-17 at 5 03 47 pm](https://cloud.githubusercontent.com/assets/12838699/23084991/1d2ee914-f533-11e6-82f7-4f5e1b95d11a.png)

![screen shot 2017-02-17 at 5 53 05 pm](https://cloud.githubusercontent.com/assets/12838699/23086271/00da751a-f53a-11e6-875d-7f1ed9ffe069.png)

This is what it looks like when this error pops up.
