### ISSUE TITLE
Error: Column start (1268) greater than line length (25)

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-stylelint#79]
![image](https://cloud.githubusercontent.com/assets/224636/12877393/a5513390-cde0-11e5-9c8e-74b893f36808.png)

Happens the second I remove a quote (happens all the time for other stuff too but this time I caught it).

```css
/**
 * Multi-line comment
 */

.selector-1,
.selector-2,
.selector-3[type=text"] {
  background: linear-gradient(#fff, rgba(0, 0, 0, 0.8));
  box-sizing: border-box;
  display: block;
  color: #333;
}

.selector-a,
.selector-b {
  padding: 10px !important;
  top: calc(calc(1em * 2) / 3);
}

.selector-x { width: 10%; }
.selector-y { width: 20%; }
.selector-z { width: 30%; }

/* Single-line comment */

@media (min-width >= 60em) {
  .selector {
    /* Flush to parent comment */
    transform: translate(1, 1) scale(3);
  }
}

@media (min-orientation: portrait), projection and (color) {
  .selector-i + .selector-ii {
    background: color(rgb(0, 0, 0) lightness(50%));
    font-family: helvetica, arial, sans-serif;
  }
}

/* Flush single line comment */
@media screen and (min-device-pixel-ratio: 2),
  screen and (min-resolution: 192dpi),
  screen and (min-resolution: 2dppx) {

  .selector {
    background-image:
      repeating-linear-gradient(
        -45deg,
        transparent,
        #fff 25px,
        rgba(255, 255, 255, 1) 50px
      );
    margin: 10px;
    margin-bottom: 5px;
    box-shadow:
      0 1px 1px #000,
      0 1px 0 #fff,
      2px 2px 1px 1px #ccc inset;
    height: 10rem;
  }

  /* Flush nested single line comment */
  .selector::after {
    content: "→";
    background-image: url("x.svg");
  }
}
```

```js
// stylelint.config.js
module.exports = {
  'plugins': [
    'stylelint-statement-max-nesting-depth'
  ],
  'rules': {
    // Plugins
    'statement-max-nesting-depth': [3, {
      countAtRules: false,
      countedNestedAtRules: false
    }],

    // String
    'string-quotes': 'single',

    // Color
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'color-no-named': true,

    // Number
    'number-leading-zero': 'always',
    'number-max-precision': 3,
    'number-no-trailing-zeros': true,
    'number-zero-length-no-unit': true,

    // Function
    'function-calc-no-unspaced-operator': true,
    'function-comma-space-after': 'always',
    'function-comma-space-before': 'never',
    'function-linear-gradient-no-nonstandard-direction': true,

    // Value list
    'value-list-comma-space-after': 'always',
    'value-list-comma-space-before': 'never',

    // Unit
    'unit-blacklist': ['em', 'rem'], // Disallow these because PostCSS adds them

    // Declaration
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-no-important': true, // Ask DG if this is causing you problems

    // Declaration block
    'declaration-block-semicolon-newline-after': 'always-multi-line',
    'declaration-block-semicolon-space-after': 'always-single-line',

    // Block
    'block-closing-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always-multi-line',
    'block-closing-brace-space-before': 'always-single-line',
    'block-no-empty': true,
    'block-opening-brace-newline-after': 'always-multi-line',
    'block-opening-brace-space-after': 'always-single-line',
    'block-opening-brace-space-before': 'always',

    // Selector
    'selector-combinator-space-after': 'always',
    'selector-combinator-space-before': 'always',
    'selector-no-id': true,
    'selector-no-type': true, // Ask DG if this is causing you problems
    'selector-no-universal': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-colon-notation': 'double',

    // Selector list
    'selector-list-comma-space-after': 'always-single-line',
    'selector-list-comma-space-before': 'never',

    // Rules
    'rule-nested-empty-line-before': ['always', {
      except: ['first-nested'],
      ignore: ['after-comment']
    }],
    'rule-no-duplicate-properties': true,
    'rule-no-shorthand-property-overrides': true,
    'rule-non-nested-empty-line-before': ['always-multi-line', {
      ignore: ['after-comment']
    }],
    'rule-properties-order': [
      {
        emptyLineBefore: true,
        properties: [
          'content'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'position',
          'top',
          'right',
          'bottom',
          'left',
          'z-index'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'align-content',
          'align-items',
          'align-self',
          'flex',
          'flex-basis',
          'flex-direction',
          'flex-flow',
          'flex-grow',
          'flex-shrink',
          'flex-wrap',
          'justify-content',
          'order'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'display',
          'float',
          'height',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'max-height',
          'max-width',
          'min-height',
          'min-width',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'table-layout',
          'width'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'font-family',
          'font-size',
          'font-style',
          'font-weight',
          'letter-spacing',
          'line-height',
          'text-align',
          'text-decoration',
          'text-overflow'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'appearance',
          'background',
          'background-attachment',
          'background-blend-mode',
          'background-color',
          'background-image',
          'background-position',
          'background-repeat',
          'background-size',
          'border',
          'border-top',
          'border-right',
          'border-bottom',
          'border-left',
          'border-radius',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-bottom-right-radius',
          'border-bottom-left-radius',
          'box-shadow',
          'color',
          'cursor',
          'mix-blend-mode',
          'opacity',
          'overflow',
          'overflow-x',
          'overflow-y',
          'visibility'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'animation',
          'animation-delay',
          'animation-direction',
          'animation-duration',
          'animation-fill-mode',
          'animation-iteration-count',
          'animation-name',
          'animation-play-state',
          'animation-timing-function',
          'transform',
          'transition'
        ]
      }
    ],
    'rule-trailing-semicolon': 'always',

    // Media
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',

    // Custom media
    'custom-media-pattern': 'xs|sm|md|lg|xlg|xxlg.+/',

    // Media query
    'media-query-parentheses-space-inside': 'never',

    // At rule
    'at-rule-empty-line-before': ['always', {
      except: ['blockless-group', 'first-nested'],
      ignore: ['after-comment']
    }],
    'at-rule-no-vendor-prefix': true,

    // Comment
    'comment-whitespace-inside': 'always',

    // General
    'indentation': 2,
    'no-eol-whitespace': true,
    'no-missing-eof-newline': true
  }
}
```

Originally ran into this and opened an issue here: https://github.com/atom-community/linter/issues/1069

Then I went to stylelint to open an issue: https://github.com/stylelint/stylelint/issues/688 and was pointed here.

@Arcanemagus @davidtheclark can we get to the bottom of this? It happens so frequently it makes linter-stylelint unusable.
